version: '3.4'

volumes:
  pulsardata:
  pulsarconf:

services:
  consumertest:
    image: ${DOCKER_REGISTRY-}consumertest
    depends_on:
      - pulsar
    build:
      context: .
      dockerfile: ConsumerTest/Dockerfile

  pulsarconnector:
    image: ${DOCKER_REGISTRY-}pulsarconnector
    depends_on:
      - pulsar
    build:
      context: .
      dockerfile: PulsarConnector/Dockerfile

  pulsar:
    image: apachepulsar/pulsar:2.6.0
    ports:
      - 8080:8080
      - 6650:6650
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    environment:
      BOOKIE_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: /bin/bash -c "bin/pulsar standalone"

  express:
    image: bbonnin/pulsar-express:0.5.1
    depends_on:
      - pulsar
    ports:
      - 3000:3000
    environment:
      PE_CONNECTION_URL: http://pulsar:8080